### ISSUE TITLE
Feature Request: Send `recordingDiscordBegan` and `recordingDiscordStopped` when started via discord commands

### ISSUE THREAD

**Issue by ep1cman** [SoTrxII/Pandora#1]
Currently the `recordingDiscordBegan` and `recordingDiscordStopped` messages are only published when a recording is started/stopped via redis. It would be super helpful if they were also published when run via commands in the discord chat. 

Currently you can only control pandora externally from something that has awareness of discord channel IDs, if this feature was implemented pandora could trigger things that don't have any awareness of discord or pandora for that matter. For example it could be used to automatically kick off the cooking process.

**Comment by SoTrxII** [comment]
Oh, never thought of that. That would be a nice addition, and it shouldn't require much changes. I'll look into it.

**Comment by SoTrxII** [comment]
Ok it's live. I just tested it with both Redis on and off. Thanks for the suggestion.
