### ISSUE TITLE
No auto-record?

### ISSUE THREAD

**Issue by ndcrd** [SoTrxII/Pandora#9]
It is such a shame current iteration of bot leans so much on manual prompting through interactions within bot (I don't consider the pubsub) Current UnifiedController is unable to act as IController inside pandora.ts due missing functions of sending events. Yet also I can't use the original IController methods there either? such unflexible thing to have. So basically you can set any client listeners inside pandora.ts to make bot autojoin, but not autorecord and stop it :(
I suppose you can re-utilize audioRecorder functions to start and stop audio recording, yet why can't I just reutilize the onStart and onStop functions inside bot client with current version of controller?

**Comment by SoTrxII** [comment]
Hey,
I'm not quite following. What would you like to do ? 
Which event/trigger would start the recording ?

Any IController implementation can start the recording by firing a 'start' event with the proper payload.  
If you're trying to build a new way to start recording, you can create a new IController implementation that suits your needs (which you can of course make a PR for).

**Comment by ndcrd** [comment]
Hi! I am sorry if you lost in context, English is not my primary language, but I'll do my best to explain myself. I was trying to do autorecording through listeners on the client. Once there are more than 2 users the bot should join and record conversation. Once the auto-join is the easiest part to setup with Eris library right in pandora.ts, the recording part seems to be tricky.
I've tried to use  [onStartCommand](https://github.com/SoTrxII/Pandora/blob/7b0a21dd4d70981b5e0736df2ab83e52c98774cc/src/Pandora.ts#L105C9-L105C23) and the onEndCommand, which should fire "start" event, but it's require a IController. But the issue is, I can't use the `this.unifiedController` as parameter in these functions, since typescript start to spewing errors, that Unified controller does not have events that IController has. Yet if I try to inject IController, whole bot just flops. I haven't found any proper ways to autorecord yet, but I've thought maybe I am just missing something.

**Comment by ndcrd** [comment]
UPD: I've managed to set an event emitters to unified controller which will fire once function has been call thus starting or ending a recording when more then N users joined a channel and stop the record once N users has left. Gonna test it out and possibly add a pr :)
